### ISSUE TITLE
Error on `require()`

### ISSUE THREAD

**Issue by jackmcdade** [pespantelis/vue-typeahead#1]
I get the following error just by requiring the component. I'm using Browserify.

`Uncaught TypeError: Cannot redefine property: $url`

![screen shot 2015-08-25 at 11 10 46 pm](https://cloud.githubusercontent.com/assets/44739/9484771/aa3e95bc-4b7e-11e5-87cb-14f4efda371a.png)

**Comment by pespantelis** [comment]
Oh sorry! I need to update the package version, in order getting the last changes (287cd57).

However, the error occurred because the vue-resource was included two times (one from you and one from typeahead component).

Thanks :)
