### ISSUE TITLE
cannot find module "vue-resource"

### ISSUE THREAD

**Issue by vdclouis** [pespantelis/vue-typeahead#10]
I'm getting this error?
Any idea?

<img width="755" alt="screen shot 2016-01-16 at 12 43 30" src="https://cloud.githubusercontent.com/assets/1033998/12372186/0a67fd20-bc4f-11e5-9e52-19b842fcc156.png">

**Comment by pespantelis** [comment]
You should use the [babel](https://babeljs.io/) to compile the script.

**Comment by vdclouis** [comment]
I have babel configured, it works fine for vue-resource and vue-router.

**Comment by alexander-elgin** [comment]
So how to fix the issue? Can you provide detailed directions, please?
