### ISSUE TITLE
unmark first item as current

### ISSUE THREAD

**Issue by im-n1** [pespantelis/vue-typeahead#12]
Hi there,

jsut a quick fix

When you get data from server, do not set first item (delete this line https://github.com/pespantelis/vue-typeahead/blob/master/vue-typeahead.js#L60) as current. First item is current when you hit arrrow down.

**Comment by im-n1** [comment]
#13

**Comment by im-n1** [comment]
Hey guys, is there any chance of merge?

**Comment by pespantelis** [comment]
Hey @grafa, according to the Algolia search engine (IMO the best search engine right now) you are right!

Also your solution is imperfect (#13).

Check my solution here 381b824.

Thanks for your interest and sorry for the delay!
