### ISSUE TITLE
about the demo

### ISSUE THREAD

**Issue by njusmx** [pespantelis/vue-typeahead#19]
Would you mind upload the source code of the demo? I have a little difficulty in using the component, maybe a little more example would help me. Thanks a lot!

**Comment by pespantelis** [comment]
Hi @njusmx!

The demo exists in [`gh-pages`](https://github.com/pespantelis/vue-typeahead/tree/gh-pages) branch. :)

**Comment by njusmx** [comment]
thanks a lot. :)
