### ISSUE TITLE
Parent Watching event

### ISSUE THREAD

**Issue by jackmcdade** [pespantelis/vue-typeahead#2]
Is there any way to watch this component from my main vm and bind other events on `isDirty` etc? I'd like to hide some of my UI when results are showing.

**Comment by jackmcdade** [comment]
Okay I figured this out. you can add `v-ref="search"` on the `<typeahead>` compontant tag and reference it's data elsewhere with `$.search.items` or other vars.

**Comment by pespantelis** [comment]
:+1:
