### ISSUE TITLE
A proper way to import it to a .vue file

### ISSUE THREAD

**Issue by Mirdrack** [pespantelis/vue-typeahead#20]
Hello!

Could you pleas tell me how is the proper way to include the package where you are working with .vue files?

I just create a project with vue-cli

```
$ npm install -g vue-cli
$ vue init webpack my-project
$ cd my-project
$ npm install
$ npm run dev
```

And this is my component

```
<template>
    <div class="autocomplete">

    </div>
</template>

<script>
VueTypeaheadMixin = require('vue-typeahead');

export default {

    mixins: [VueTypeaheadMixin],

    ready () {

        console.log('Autocomplete');
    },
}
</script>

<style type="text/css">
</style>
```

But I'm receiving 
vue-typeahead.js?51da:1 Uncaught SyntaxError: Unexpected token import
This error when the webpack tries to transpile the code
How can avoid this?

If you need more information just let me know, thanks in advance

**Comment by hansnow** [comment]
the same problem
