### ISSUE TITLE
Query parameter is not sended in request

### ISSUE THREAD

**Issue by a47ae** [pespantelis/vue-typeahead#23]
Hey, when I tried out your component I recognized that the query parameter does not got send along with my request. I double checked in the ChromeDev tools but there is no GET parameter in the rquest send by vue-resource. But if I change the line 
[`return this.$http.get(this.src, Object.assign(queryParam, this.data))`](https://github.com/pespantelis/vue-typeahead/blob/master/src/main.js#L64) to 
`return this.$http.get(this.src, {params: Object.assign(queryParam, this.data)})` 
everything works as expected.

So maybe the `params` option needs to be statet explicitly?

**Comment by weklund** [comment]
Wait so you're saying what you're passing isn't working at all?

**Comment by alons182** [comment]
I have the same problem, the query parameter is not sended

**Comment by a47ae** [comment]
So this is what the request looks like with the original code:
![without_params](https://cloud.githubusercontent.com/assets/10907455/16382118/c3363078-3c7f-11e6-86eb-67395b6138a3.png) - there is not query parameter.

And this is the modified code where I added `params:` 
![with_params](https://cloud.githubusercontent.com/assets/10907455/16382213/3a662220-3c80-11e6-85c2-56e7fed0cb8f.png)
In the [vue-resource documentation](https://github.com/vuejs/vue-resource/blob/master/docs/http.md) the syntax for get is `get(url, [options])` so one have to pass a params option. Maybe they changed the syntax in the recent version?

**Comment by alons182** [comment]
Exactly, with your change works fine (return this.$http.get(this.src, {params: Object.assign(queryParam, this.data)}) )

**Comment by pespantelis** [comment]
Thanks @a47ae for the issue!

This is related with the recent changes on `vue-resource` as you said.
I'll change it when I'll publish the next major release with the `vue@2.0`.

Until then, we could use the `vue-resource@0.8` :)

**Comment by a47ae** [comment]
Thanks for clearing that up! 
Looking forward to the next release. :)

**Comment by b8ne** [comment]
Hi I am also experiencing this problem, I have just installed everything so assuming I have the latest versions.

package.json
`{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.4",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^1.0.26",
    "vue-resource": "^0.9.3"
  },
  "dependencies": {
    "vue-typeahead": "^2.2.1"
  }
}`

Typehead.vue - script
`import VueTypeahead from 'vue-typeahead'

```
export default {
    extends: VueTypeahead, // vue@1.0.22+
    // mixins: [VueTypeahead], // vue@1.0.21-

    data () {
        return {
            // The source url
            // (required)
            src: '../../../api/players',

            // Limit the number of items which is shown at the list
            // (optional)
            limit: 1,

            // The minimum character length needed before triggering
            // (optional)
            minChars: 1,

            queryParamName: 'name',
        }
    },

    methods: {
        // The callback function which is triggered when the user hits on an item
        // (required)
        onHit (item) {
            console.log(item)
        },

        // The callback function which is triggered when the response data are received
        // (optional)
        prepareResponseData (data) {
            // data = ...
            for (let item of data) {
                console.log(item.firstName);
            }
            return data
        }
    }
}`
```

EDIT\* sorry got mixed up on repos, i applied this fix manually and all is working, just realised PR hasnt been merged yet
