### ISSUE TITLE
fetch method [vue-resource]

### ISSUE THREAD

**Issue by npulidom** [pespantelis/vue-typeahead#27]
I couldn't set GET params data for request via component props.
I managed to override the component `fetch()` method and set params data like:

``` javascript
methods: {
       onHit(item) {
            console.log("onhit", item);
        },
        prepareResponseData(data) {
            console.log("prepareResponseData", data);
            return data;
        },
       //@override
       fetch() {

            var opts = {
                params : {
                    "foo" : "bar"
                }
            }

            return this.$http.get(this.url, opts);
        }
    }
```

It's possible that **vue-resource** was taking params as config input.
[vue-resource api](https://github.com/vuejs/vue-resource/blob/master/docs/http.md)

**Comment by jordij** [comment]
Yes, same here. I had to override fetch and replace last line of the function with

```
return this.$http.get(src, { params: params })
```

**Comment by pespantelis** [comment]
Duplicate #23
