### ISSUE TITLE
Optional Preference to disable the appending of the trailing / in http url requests.

### ISSUE THREAD

**Issue by EHackettTriCore** [pespantelis/vue-typeahead#31]
The plugin works wonderfully however, in our environment, our api endpoints don't have trailing '/' in our urls. ATM I have to comment out the snippet that appends a trailing slash. You probably don't need those lines if you let the users decide whether or not to at a trailing forward slash.

```
if (this.src.substr(-1) !== '/') {
   this.src += '/'
}
```

**Comment by Schw2iizer** [comment]
I just realized I may have left a similar issue. I'll give this a shot.

Thanks!

**Comment by Schw2iizer** [comment]
I commented out that code and it doesn't have any affect on the trailing '/'. Did you do anything else? @EHackettTriCore

**Comment by pespantelis** [comment]
Hi guys and sorry for the delayed response!

I have already reverted these lines (4dc1536) to avoid related issues.
I apologize for any inconvenient.

Thanks!
