### ISSUE TITLE
Use local resource for lookup

### ISSUE THREAD

**Issue by blackfyre** [pespantelis/vue-typeahead#37]
Hi!

Thanks for the great component! It helped me a few time already, but I came across a new request and I'm unsure how to solve this one.
The problem is that I'm trying to implement this as a part of a tag/token selector, and all the possible tags/tokens are already available locally and there's no actual need for an ajax request, but the component only supports remote requests.

Could this component be extended to optionally support local resources?

**Comment by pespantelis** [comment]
Hi @blackfyre!

Please check the issue #25.

**Comment by blackfyre** [comment]
Wonderful!

Thanks!
