### ISSUE TITLE
Display selected

### ISSUE THREAD

**Issue by thanosalexander** [pespantelis/vue-typeahead#38]
Hi .. is there any way to display selected item after i select from list?
also the only way i found to sync with my data (user_id) is to  add this this.$emit('input', item.id)
on onHit method.

Also one small issue on handling @keydown.enter event. when i click enter it submits the form.i tried add @keydown.enter.prevent  or @keydown.enter.stop but no luck

**Comment by mailnike** [comment]
@thanosalexander how did you solve all issues?

**Comment by marsPure** [comment]
same issue, any solution?

**Comment by vmitchell85** [comment]
See what I did here: https://github.com/pespantelis/vue-typeahead/issues/35#issuecomment-393605395
