### ISSUE TITLE
Using in Vue 2 pulls in copy of Vue 1

### ISSUE THREAD

**Issue by oldskool73** [pespantelis/vue-typeahead#40]
Hi,

I'm using this under `Vue @ ^2.0.1`, and noticed that in my compiled source when I include `vue-typeahead` there's also a full copy of `Vue @ 1.0.28` included, adding ~90k of unneeded code after compression. If I remove `node_modules/vue-typeahead/node_modules/vue` this goes away, and it just uses Vue 2 as expected. 

I believe all your `dependencies` should maybe just be `devDependencies`, so a package local copy of an old Vue doesn't get installed?

**Comment by RomanLavrinenko** [comment]
Totally agree, faced with the same issue, please do this

**Comment by amanpatel** [comment]
+1

**Comment by mridang** [comment]
+1

**Comment by ClaraLeigh** [comment]
+1 this is also breaking vue-devtools for me

EDIT: 
Remade it myself, only a few lines of code.
Leaving my comment here incase anyone else gets the same issue.

Error seen in console while attempting to use chrome dev-tools was: 
Uncaught TypeError: Cannot read property 'type' of undefined 

Dev tools also showed (although using v2): 
[vue-devtools] Ready. Detected Vue v1.0.28

**Comment by DanCroweNH** [comment]
+1
