### ISSUE TITLE
items not always populated with latest results

### ISSUE THREAD

**Issue by JoolsMcFly** [pespantelis/vue-typeahead#46]
Hi,

first of all thanks for your component. It's easy to use and works well.

Howeve, I sometimes come across an issue where the latest query completes before previous ones.
For instance, if I type "something" it will trigger the following queries:
"som"
"some"
"somet"
"someth"
"somethi"
"somethin"
"something"

Sometimes query for "some" will complete after "something" so final items are not the ones that match "something" but those of "some". Bummer.

I've implemented a solution and will submit for review.

Thanks.

**Comment by pespantelis** [comment]
Thanks!
