### ISSUE TITLE
trap the delete event on typeahead component

### ISSUE THREAD

**Issue by siavash13** [pespantelis/vue-typeahead#48]
I have used typeahead as component in my project and so far it's been useful, now I need to trap the `delete` and `backspace` buttons when clicked, but I have no idea how to trap these events in `typeahead component` could you please help me through this issue?

**Comment by pespantelis** [comment]
Vue.js captures both `Delete` & `Backspace` keys by using the `.delete` key modifier [[#ref](https://vuejs.org/v2/guide/events.html#Key-Modifiers)].

So, you could try something like this:
```vue
<template>
  <input type="text" @keydown.delete="onDelete"/>
</template>

<script>
export default {
  methods: {
    onDelete (event) {
      if (event.key === 'Delete') {
        console.log('Delete')
      } else {
        console.log('Backspace')
      }
    }
  }
}
</script>
```
