### ISSUE TITLE
Vue 1.0 support

### ISSUE THREAD

**Issue by warksit** [pespantelis/vue-typeahead#7]
Do you plan to release support for vue 1.0?

**Comment by pespantelis** [comment]
Hi @warksit, thanks for the interest!

I would like to inform you that I have intended to upgrade the component to support the latest version of `vue`. My time is limited, but I will do my best to be done as soon as possible.

Feel free to contribute if you want :)

**Comment by pespantelis** [comment]
e32362aa7fe9f52786a6b05493fa0102f10ab88b
